Repository 2023-chambit-project/KOOSMOOS, pull requests merged in 2023-08, with the labels that each got.

#8 feat: Box 공용 컴포넌트를 추가합니다.
  src/components/Box/Box.styles.ts
  src/components/Box/Box.types.ts
  src/components/Box/index.tsx
  src/components/index.ts
Labels: feat

#10 feat: footer 컴포넌트 작업 완료했습니다.
  src/components/Layout/Footer/Footer.styles.ts
  src/components/Layout/Footer/Footer.tsx
  src/components/layout/index.tsx
Labels: feat

#11 fix: routing 설정 방식을 변경합니다.
  src/App.tsx
  src/Routers/routing.tsx
  src/routes/routing.tsx
Labels: fix

#23 chore: @tanstack/react-query 환경 구성
  package.json
  src/App.tsx
  yarn.lock
Labels: init

#22 fix: Footer 반응형 문제 수정
  src/components/Layout/Footer/Footer.styles.ts
Labels: fix

#25 #24 게임 페이지 퍼블리싱
  public/assets/img/CelestialBodies.svg
  public/assets/img/FlagMoon.svg
  src/components/Layout/Footer/Footer.styles.ts
  src/constants/gameItems.ts
  src/constants/index.ts
  src/pages/Game/Game.styles.ts
  src/pages/Game/Game.types.ts
  src/pages/Game/components/AlignedBox/AlignedBox.styles.ts
  src/pages/Game/components/AlignedBox/index.tsx
  src/pages/Game/components/SideOpenDescription/SideOpenDescription.styles.ts
  src/pages/Game/components/SideOpenDescription/index.tsx
  src/pages/Game/index.tsx
  yarn.lock
Labels: publishing

#26 #16 뉴스 페이지 퍼블리싱 및 기능 구현
  public/assets/bg/purple_bg.png
  public/assets/bg/space-bg.png
  src/components/SpringMotionBox/index.tsx
  src/components/index.ts
  src/constants/index.ts
  src/constants/queryKeys.ts
  src/hooks/index.ts
  src/hooks/useYscroll.tsx
  src/pages/News/News.styles.ts
  src/pages/News/components/Card/Card.styles.ts
  src/pages/News/components/Card/index.tsx
  src/pages/News/components/ShootingStar/ShootingStart.styles.ts
  src/pages/News/components/ShootingStar/index.tsx
  src/pages/News/index.tsx
  src/services/apis/index.ts
  src/services/apis/news.ts
  src/services/index.ts
  src/services/queries/index.ts
  src/services/queries/news.ts
  src/styles/common.tsx
  src/types/index.ts
  src/types/news.ts
  yarn.lock
Labels: feat
