Repository 2023-chambit-project/KOOSMOOS, pull requests merged in 2023-09, with the labels that each got.

#29 #28 msw 환경 세팅을 마무리
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/mocks/apis/index.ts
  src/mocks/apis/test.ts
  src/mocks/browser.ts
  src/mocks/handlers.ts
  yarn.lock
Labels: init

#31 #24 게임2 페이지 - 주요 기능 구현을 마무리합니다.
  package.json
  public/assets/game/resultPaper/ENFJ.png
  public/assets/game/resultPaper/ENFP.png
  public/assets/game/resultPaper/ENTJ.png
  public/assets/game/resultPaper/ENTP.png
  public/assets/game/resultPaper/ESFJ.png
  public/assets/game/resultPaper/ESFP.png
  public/assets/game/resultPaper/ESTJ.png
  public/assets/game/resultPaper/ESTP.png
  public/assets/game/resultPaper/INFJ.png
  public/assets/game/resultPaper/INFP.png
  public/assets/game/resultPaper/INTJ.png
  public/assets/game/resultPaper/INTP.png
  public/assets/game/resultPaper/ISFJ.png
  public/assets/game/resultPaper/ISFP.png
  public/assets/game/resultPaper/ISTJ.png
  public/assets/game/resultPaper/ISTP.png
  src/assets/lottie/locket.json
  src/assets/lottie/satellite.json
  src/components/index.ts
  src/components/progressBar/index.tsx
  src/components/progressBar/progressBar.styles.ts
  src/components/progressBar/progressBar.types.ts
  src/constants/gameItems.ts
  src/hooks/index.ts
  src/hooks/useLoading.ts
  src/mocks/apis/game/apis.ts
  src/mocks/apis/game/index.ts
  src/mocks/apis/index.ts
  src/mocks/apis/test.ts
  src/pages/Game/Game1/index.tsx
  src/pages/Game/Game2/Game2.constants.ts
  src/pages/Game/Game2/Game2.styles.ts
  src/pages/Game/Game2/Game2.types.ts
  src/pages/Game/Game2/components/IntroSection/IntroSection.styles.ts
  src/pages/Game/Game2/components/IntroSection/index.tsx
  src/pages/Game/Game2/components/Loading/Loading.styles.ts
  src/pages/Game/Game2/components/Loading/index.tsx
  src/pages/Game/Game2/components/ResultSection/Result.styles.ts
  src/pages/Game/Game2/components/ResultSection/index.tsx
  src/pages/Game/Game2/components/TestSection/TestSection.styles.ts
  src/pages/Game/Game2/components/TestSection/index.tsx
  src/pages/Game/Game2/components/index.ts
  src/pages/Game/Game2/index.tsx
  src/pages/Game/components/AlignedBox/index.tsx
  src/pages/Game/components/SideOpenDescription/SideOpenDescription.styles.ts
  src/routes/routing.tsx
  src/services/apis/game.ts
  src/services/apis/index.ts
  src/services/queries/game.ts
  src/services/queries/index.ts
  src/styles/themes/palette.ts
  src/types/game.ts
  src/types/index.ts
  yarn.lock
Labels: feat

#34 #33 Header 세부 문제 해결 및 Layout 구조를 수정합니다.
  public/assets/font/PyeongChangPeace-Bold.otf
  public/assets/font/PyeongChangPeace-Light.otf
  src/components/Layout/Header/Header.styles.ts
  src/components/Layout/Header/Header.tsx
  src/constants/mainNav.ts
  src/main.tsx
  src/styles/font.css
  src/styles/global.tsx
Labels: fix

#35 #33 Footer 세부 문제 해결 및 Layout 구조를 수정합니다.
  src/components/Layout/Footer/Footer.styles.ts
  src/components/Layout/Footer/Footer.tsx
  src/styles/font.css
  src/styles/global.tsx
Labels: fix

#36 #3 공용 컴포넌트 중 Button 디자인 수정한 버전을 추가했습니다.
  src/components/ButtonV2/ButtonV2.styles.ts
  src/components/ButtonV2/ButtonV2.types.ts
  src/components/ButtonV2/index.tsx
Labels: feat
