Repository 2023-chambit-project/KOOSMOOS, pull requests merged in 2023-12, with the labels that each got.

#49 axios instance를 생성합니다.
  src/services/apis/axios.ts
  src/services/apis/index.ts
Labels: feat

#47 #46 Suspense 및 ErrorBoundary를 적용합니다.
  package.json
  public/assets/img/error_astronaut.png
  src/App.tsx
  src/assets/lottie/loading_rocket.json
  src/assets/lottie/rocket.json
  src/components/ErrorAstronaut/ErrorAstronaut.styles.ts
  src/components/ErrorAstronaut/ErrorAstronaut.tsx
  src/components/ErrorAstronaut/index.ts
  src/components/LoadingRocket/LoadingRocket.styles.ts
  src/components/LoadingRocket/LoadingRocket.tsx
  src/components/LoadingRocket/index.ts
  src/components/index.ts
  src/pages/Game/Game2/components/IntroSection/index.tsx
  yarn.lock
Labels: feat

#41 #24 Game 1 Page 기능 구현
  package.json
  public/assets/game/game1/Fixture.svg
  public/assets/game/game1/FullMoon.png
  public/assets/game/game1/WhiteStarParticle.png
  src/App.tsx
  src/assets/lottie/space_rock.json
  src/assets/lottie/telescope.json
  src/atoms/curFlagIndex.atom.ts
  src/atoms/flagList.atom.ts
  src/atoms/moonShape.atom.ts
  src/atoms/sidePanelMode.atom.ts
  src/atoms/viewType.atom.ts
  src/mocks/apis/game/apis.ts
  src/mocks/data/game.ts
  src/pages/Game/Game1/Game1.constants.ts
  src/pages/Game/Game1/Game1.styles.ts
  src/pages/Game/Game1/Game1.types.ts
  src/pages/Game/Game1/components/GeneralMoonView/GeneralMoonView.styles.ts
  src/pages/Game/Game1/components/GeneralMoonView/components/Pointer/Pointer.styles.ts
  src/pages/Game/Game1/components/GeneralMoonView/components/Pointer/index.tsx
  src/pages/Game/Game1/components/GeneralMoonView/index.tsx
  src/pages/Game/Game1/components/Loading/Loading.styles.ts
  src/pages/Game/Game1/components/Loading/index.tsx
  src/pages/Game/Game1/components/MagnifiedMoonView/ MagnifiedMoonView.styles.ts
  src/pages/Game/Game1/components/MagnifiedMoonView/components/Carousel/Carousel.styles.ts
  src/pages/Game/Game1/components/MagnifiedMoonView/components/Carousel/index.tsx
  src/pages/Game/Game1/components/MagnifiedMoonView/components/Flag/Flag.styles.ts
  src/pages/Game/Game1/components/MagnifiedMoonView/components/Flag/index.tsx
  src/pages/Game/Game1/components/MagnifiedMoonView/index.tsx
  src/pages/Game/Game1/components/SidePanel/SidePanel.styles.ts
  src/pages/Game/Game1/components/SidePanel/components/FlagAddingForm/FlagAddingForm.styles.ts
  src/pages/Game/Game1/components/SidePanel/components/FlagAddingForm/index.tsx
  src/pages/Game/Game1/components/SidePanel/components/VerticalList/VerticalList.styles.ts
  src/pages/Game/Game1/components/SidePanel/components/VerticalList/index.tsx
  src/pages/Game/Game1/components/SidePanel/components/index.tsx
  src/pages/Game/Game1/components/SidePanel/index.tsx
  src/pages/Game/Game1/components/index.ts
  src/pages/Game/Game1/helpers/createFlagFormHelper.ts
  src/pages/Game/Game1/helpers/getPointerPropsHelper.ts
  src/pages/Game/Game1/index.tsx
  src/pages/Game/components/AlignedBox/AlignedBox.styles.ts
  src/pages/Game/components/SideOpenDescription/SideOpenDescription.styles.ts
  src/pages/Game/components/SideOpenDescription/index.tsx
  src/pages/Game/components/index.ts
  src/pages/Game/index.tsx
  src/services/apis/game.ts
  src/services/queries/game.ts
  src/types/game.ts
  yarn.lock
Labels: feat

#52 Game1 버튼 컴포넌트 이름 변경 (ButtonV2->Button)
  src/pages/Game/Game1/components/MagnifiedMoonView/index.tsx
  src/pages/Game/Game1/components/SidePanel/components/FlagAddingForm/index.tsx
  src/pages/Game/Game1/components/SidePanel/index.tsx
Labels: fix

#53 feat: 갤러리 페이지 퍼블리싱 및 기능 구현
  package.json
  public/assets/bg/PaleBlueDot.png
  src/constants/queryKeys.ts
  src/pages/Gallery/Gallery.styles.ts
  src/pages/Gallery/components/MenuBar/MenuBar.styles.ts
  src/pages/Gallery/components/MenuBar/MenuBar.tsx
  src/pages/Gallery/components/MenuBar/MenuBar.types.ts
  src/pages/Gallery/components/MenuBar/index.ts
  src/pages/Gallery/components/PictureItem/PictureItem.styles.ts
  src/pages/Gallery/components/PictureItem/PictureItem.tsx
  src/pages/Gallery/components/PictureItem/PictureItem.types.ts
  src/pages/Gallery/components/PictureItem/index.ts
  src/pages/Gallery/components/PictureList/PictureList.styles.ts
  src/pages/Gallery/components/PictureList/PictureList.tsx
  src/pages/Gallery/components/PictureList/PictureList.types.ts
  src/pages/Gallery/components/PictureList/index.ts
  src/pages/Gallery/components/index.ts
  src/pages/Gallery/gallery.constants.ts
  src/pages/Gallery/gallery.types.ts
  src/pages/Gallery/index.tsx
  src/services/apis/gallery.ts
  src/services/apis/index.ts
  src/services/queries/gallery.ts
  src/types/gallery.ts
  src/types/index.ts
  yarn.lock
Labels: feat

#59 chore: favicon과 title 적용
  index.html
  public/logo.svg
Labels: chore

#56 refactor: axios → axiosInstance로 적용
  src/services/apis/game.ts
  src/services/apis/techWiki.ts
Labels: refactor

#61 fix: 경로 수정
  src/services/apis/game.ts
  src/services/apis/techWiki.ts
Labels: fix

#55 404Page 작업했습니다.
  public/assets/img/lost_astronaut.webp
  src/pages/Not-found/NotFound.styles.ts
  src/pages/Not-found/index.tsx
  src/routes/routing.tsx
Labels: publishing
