Repository 2023-chambit-project/KOOSMOOS, pull requests merged in 2024-01, with the labels that each got.

#66 MainPage, Scrollerbar 중첩되는 문제 해결했습니다.
  src/pages/Main/Main.styles.ts
  src/styles/global.tsx
Labels: fix

#68 Loading 화면(Suspense fallback) 레이아웃 이슈 해결
  src/App.tsx
  src/components/Layout/index.tsx
Labels: fix

#70 라우팅 주소를 객체로 관리하여 재사용 가능하도록 리팩터링
  src/constants/gameItems.ts
  src/constants/mainNav.ts
  src/pages/Game/components/AlignedBox/index.tsx
  src/routes/path.constants.ts
  src/routes/routing.tsx
Labels: refactor

#75 검사하기 링크 복사에서 환경따라 다르게 반영
  src/constants/environmentSpecificPath.ts
  src/constants/index.ts
  src/pages/Game/Game2/components/ResultSection/index.tsx
Labels: chore

#76 게임2 로딩 → 결과 페이지 렌더링 시 layout shift 이슈 해결
  src/pages/Game/Game2/Game2.styles.ts
  src/pages/Game/Game2/components/ResultSection/Result.styles.ts
Labels: fix

#77 랜딩페이지 깜빡거림 이슈 해결
  src/pages/Main/Main.styles.ts
Labels: fix
